trigger:
- main

 
pool:
  vmImage: 'ubuntu-latest'


  
steps:
- script: 
  workingDirectory: Booking.Server/
  displayName: Set working directory

- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    includePreviewVersions: true 



- task: DotNetCoreCLI@2
  displayName: .NET restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: .NET build
  inputs:
    command: build
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Booking.Server'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: Booking.Server/Booking.Server.API/Booking.Server.API.csproj
    arguments: '-o _output'
    zipAfterPublish: false
    modifyOutputPath: false

- script: dotnet test Booking.Server/ --logger trx
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/Booking.Server/Booking.Server.Test/TestResults/*.trx'
    artifactName: 'test-results'


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: _output
    artifactName: 'Booking-api'