name : Docker-CI
trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 

 

steps:
    
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'mbidzinsk/booking-api-azure'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: 'Booking.Server'